#!/bin/sh

chown root:wheel /Library/LaunchDaemons/com.michael.TimeMachine.plist
chown root:wheel /usr/libexec/TimeMachine
chmod 0755 /usr/libexec/TimeMachine
launchctl load /Library/LaunchDaemons/com.michael.TimeMachine.plist
echo "➡️Powered by @halo_michael"
echo "➡️ TimeMachine on iOS will creat a rootfs snapshot and a datafs snapshot at 2:00AM everyday;and delete the oldest snapshots when you have more than 7 snapshots."
echo "➡️ Installation successfully,Enjoy."
exit 0

