#!/bin/bash

dsnappy() {
check_orig_fs=`snappy -f / -l | grep "^orig-fs$"`
check_electra_prejailbreak=`snappy -f / -l | grep "^electra-prejailbreak$"`
if [[ "$check_orig_fs" == "orig-fs" ]]; then
	snappy -f / -r orig-fs --to com.apple.TimeMachine.orig-fs
fi
if [[ "$check_electra_prejailbreak" == "electra-prejailbreak" ]]; then
	snappy -f / -r electra-prejailbreak --to com.apple.TimeMachine.electra-prejailbreak
fi
}

dsnaputil() {
check_orig_fs=`snapUtil -l / | grep "^orig-fs$"`
check_electra_prejailbreak=`snapUtil -l / | grep "^electra-prejailbreak$"`
if [[ "$check_orig_fs" == "orig-fs" ]]; then
	snapUtil -n orig-fs com.apple.TimeMachine.orig-fs /
fi
if [[ "$check_electra_prejailbreak" == "electra-prejailbreak" ]]; then
	snapUtil -n electra-prejailbreak com.apple.TimeMachine.electra-prejailbreak /
fi
}

dchecksnapshot() {
if [ -f "/usr/bin/snappy" ];then
	dsnappy
else
	dsnaputil
fi
}

Version=`sw_vers -productVersion`
if [[ $Version == 11.* ]] || [[ $Version == 12.* ]];then
	echo "iOS11 or iOS12 founded, now checking orig snapshot..."
 	dchecksnapshot
else
	echo "iOS10 founded, skip orig snapshot check."
fi
exit 0
