include $(THEOS)/makefiles/common.mk

LIBRARY_NAME = libTimeMachine

$(LIBRARY_NAME)_FILES = libTimeMachine.m
$(LIBRARY_NAME)_LDFLAGS = -compatibility_version $(VERSION) -current_version $(VERSION)

include $(THEOS_MAKE_PATH)/library.mk
