#!/bin/bash

chown root:wheel /etc/rc.d/snapshotcheck
chmod 0755 /etc/rc.d/snapshotcheck
chown root:wheel /Library/LaunchDaemons/com.michael.TimeMachine.plist
chown root:wheel /usr/libexec/TimeMachine
chmod 0755 /usr/libexec/TimeMachine
chown root:wheel /usr/bin/setTimeMachine
chmod 0755 /usr/bin/setTimeMachine
launchctl load /Library/LaunchDaemons/com.michael.TimeMachine.plist
exit 0
